### ISSUE TITLE
Add this theme to the theme gallery

### ISSUE THREAD

**Issue by digitalcraftsman** [halogenica/beautifulhugo#1]
Hello @halogenica,

I'm sure you want to add your theme to Hugo's [theme gallery](http://themes.gohugo.io/). You can do this by adding this repository as submodule to the [hugoThemes](https://github.com/spf13/hugothemes) repository.

However, to make sure that the demo of you theme can be generated we need to add two things:

- within the `exampleSite` folder you need to have a directory named `static`, even if it's empty and not used. Since Git needs something to track inside that folder add an empty file like `.gitkeep` to this directory.
- we need some metadata about this theme. Those are defined in the `theme.toml`. You can find an example [here](https://github.com/spf13/hyde/blob/master/theme.toml)

**Comment by halogenica** [comment]
Thank you! Opened an issue to request it to be added as a submodule here:
https://github.com/spf13/hugoThemes/issues/118

**Comment by digitalcraftsman** [comment]
Great.
