### ISSUE TITLE
[QUESTION] about .RSSLink in about page

### ISSUE THREAD

**Issue by yamila-moreno** [halogenica/beautifulhugo#101]
Hi! I'm trying to migrate my blog to this theme (thanks for your work!) and I've found an unexpected behaviour.

I've "rss = true" setting in `config.toml`, so in the main page I can see the rss icon pointing to the `index.xml` file. However, in the footer of the "about.md" page, the ".RSSLink" variable is empty, so the link is wrong.

Could you provide any hint on this? Is something I have to configure? Thanks for your time! 👍

**Comment by badele** [comment]
Hi,

The **.RSSLINK** is the builtin Hugo variables, normally it contains the URL feed. You can [see more information here](https://gohugo.io/templates/rss/#reference-your-rss-feed-in-head)

You can see result in my [blog](http://blog.jesuislibre.org/) and see my actual [configuration](https://github.com/badele/blog.jesuislibre.org/blob/master/config.yaml)

Regards

**Comment by yamila-moreno** [comment]
Hi @badele thanks for your answer; I've checked you configuration, but still not understand why the default configuration (as far as I know, no configuration is default) is not working. If you have some minutes, could you take a look at this?

This is the web in production: https://moduslaborandi.net/ , at the bottom, the icon has the proper link.
And this is the `/about` page in production https://moduslaborandi.net/about/ where the rss icon doesn't have any (and points to the same page).

This is the repository: https://github.com/yamila-moreno/moduslaborandi

Best

**Comment by badele** [comment]
hi @yamila-moreno Can you test with my **[fix-rss](https://github.com/badele/beautifulhugo/tree/fix-rss)** branch ? And say me if that work ?

Thank

**Comment by yamila-moreno** [comment]
Hi @badele thanks for taking the time!! Now is working! 👍 
I've been trying to figure out why other blogs (https://lekum.org) work; but for now, I'm glad this is fixed.

Again, thank you!

**Comment by halogenica** [comment]
Thanks @yamila-moreno for letting me know, and thank you @badele for the fix! Merged: 9d53238842b583b4b126baedf1e6fa2a8f5c2aab
