### ISSUE TITLE
exampleSite/config.toml typo & suggestions

### ISSUE THREAD

**Issue by nancym** [halogenica/beautifulhugo#103]
The exampleSite config.toml includes this line:

    pygmentCodeFences = true

But it should be:

    pygmentsCodeFences = true
           ^note the s here

Suggestions:
* Please add useChroma (possibly commented out) to the `[params]` section
* Please make the README and this config.toml consistent w.r.t. `[params]` vs `[Params]`. It's confusing because I think some settings in Hugo are case sensitive.
* Maybe include some other Chroma/Pygments settings in this example config.toml, e.g. `pygmentsOptions = "linenos=table"` (probably commented out).

Thanks for such a nice theme!

**Comment by rsletta** [comment]
@halogenica - This issue can be closed. Resolved in 
https://github.com/halogenica/beautifulhugo/commit/b2ea7d970883a45bebfd8a1c054c2845ce4ba201#diff-991d2a2fe208cdee83955ad6e9a323a7

**Comment by halogenica** [comment]
Indeed, thanks!
