### ISSUE TITLE
README suggestions related to Chroma and Pygments

### ISSUE THREAD

**Issue by nancym** [halogenica/beautifulhugo#104]
In the **Chroma** section of the README, I think it would be useful to mention that if:

    pygmentsUseClasses = false

then the syntax.css file is not needed.

It would probably be more accurate to use `useChromaClasses` rather than `useChroma` for that param name, but it might be too much of a pain to change it now.

I think it would be easier to understand highlighting if that part of the README had this structure:

* Syntax highlighting
   * Server side syntax highlighting with Chroma
   * Client side syntax highlighting with Chroma
   * Server side syntax highlighting with Pygments (deprecated)
   * Client side syntax highlighting with Pygments (deprecated)

I'm still figuring out all the weirdnesses of Chroma and don't feel like I know enough to actually write those sections yet.

Thank you for beautifulhugo!

**Comment by halogenica** [comment]
Updated readme here: b17deec67435f95cf8eefee4252c3b90b771f202

Thanks!
