### ISSUE TITLE
[Question]: Hiding next | previous post buttons on static pages

### ISSUE THREAD

**Issue by arwhyte** [halogenica/beautifulhugo#108]
The Demo Beautiful Hugo site includes a static "About" page that hides the next | previous post-> button that is associated with blog entries. [1]  I'd like to hide the "post" button on my static pages as well but when I mimic the "About" page with my own "About" page the post button is displayed on it.   How does one  hide/exclude the next | previous post-> button on static pages?

My initial content directory
```
content
  page
    about.md
  post
    post1.md
   . . .
```

[1] https://themes.gohugo.io/theme/beautifulhugo/page/about/

**Comment by johanbrandhorst** [comment]
Also running into this issue :(

**Comment by henryiii** [comment]
If this solution is better, I can change my PR to do this instead.

**Comment by halogenica** [comment]
Thank you @arwhyte and @johanbrandhorst for pointing this out, and big thanks to @henryiii for fixing it! Merged: 9eea743863beb9cfb7cbe6eee4d38572a00e5471
