### ISSUE TITLE
How to implement Highlight.js 

### ISSUE THREAD

**Issue by asimumba** [halogenica/beautifulhugo#121]
Hi 

I am still quite new to Hugo and HTML and CSS generally. I'm seeking guidance on syntax highlighting. I would love to implement the `github` style using `Highlight.js`. Anyone to assist?

**Comment by jl5000** [comment]
In the Hugo lithium theme there are lines in the config file to enable this (you can also find it in my config_old file in my r-house repo)...this might work if you give it a try, although I'm new at this myself so I'm not sure.

**Comment by asimumba** [comment]
I did try that before I posted. I will try to see how I can manipulate the highlight.min.js file in the theme.
