### ISSUE TITLE
bigimg broken on Firefox 57

### ISSUE THREAD

**Issue by kevlar1818** [halogenica/beautifulhugo#122]
When I include a `bigimg` on my site, it does not show up in Firefox 57. The title text CSS seems to work, as the title turns white with a drop shadow, but it's just sitting on a white background. This problem does not occur in Chromium.

I'm running Arch Linux, Firefox 57.0.4, and Chromium 63.0.3239.132.

**Comment by jennaallen** [comment]
I'm having the same issue with both Firefox and Safari on Mac OS.
Firefox 58.0.2 and Safari 11.0.3.

**Comment by yogster** [comment]
Hey @kevlar1818 is this still an issue? I run Firefox 59.0.1 on OSX and bigimgs display fine.

Can you paste the bigimg config in your `.toml` or `.md` and the HTML that gets rendered to display the bigimg?

**Comment by halogenica** [comment]
closing due to age
