### ISSUE TITLE
update font awesome?

### ISSUE THREAD

**Issue by jlozadad** [halogenica/beautifulhugo#136]
hello,

is it possible font awesome can be updated? or describe how to do it?

**Comment by yogster** [comment]
Check out #152. You could use [ForkAwesome](https://github.com/ForkAwesome/Fork-Awesome/). I am checking to see if it would be okay to include it in a PR.

**Comment by halogenica** [comment]
Just updated to Font Awesome 5.5.0! 8a0d4892520ee86bb3462752e2cce6f86e571f43
