### ISSUE TITLE
Multiple big image not working 

### ISSUE THREAD

**Issue by whgandalf** [halogenica/beautifulhugo#14]
Hello @halogenica 

Thanks for porting beautifulhugo, I have been playing around with it and I found there was no possibility to use bigimg in the homepage, by the way I checked pages functionality and it does, so reading a little from the jekyll version I found the way to have them in the frontpage as you can see here:

[elcoliving.com](http://elcoliving.com)

By the way reading the original beautiful-jekyll docs, there is a feature to add multiple images to the pages using a list variable in the TOML config part, but when I try to apply this to beautifulhugo it doesn't work as expected: I get this:

> GET http://localhost:1313/coliving-space-bogota/[/img/1dj.jpg%20/img/1fireplace.jpg%20/img/1terraza.jpg] 404 (Not Found)

after setting the next list var at the TOML part:

`bigimg = ["/img/1dj.jpg", "/img/1fireplace.jpg", "/img/1terraza.jpg"]`

If I set the variable as a string pointing just one file, it works. finally, the question is, do you know if is it possible with the current version of beautifulhugo to use the multiple image option?

Thank you very much for taking the time reading this.

**Comment by halogenica** [comment]
Hello! Multiple bigimg is currently not supported. I've spent a day trying to add it for you and I just can't quite figure out how to replicate the behavior of the jekyll version. I would be happy to accept a pull request if you're able to figure it out! Specifically, the header_wp.html partial needs to be updated to match the behavior of beautiful-jekyll's header.html partial.

**Comment by liwenyip** [comment]
Hi, I've just proposed a pull request to add support for bigimg (and multiple bigimgs) on the front page.

I didn't add support for multiple bigimgs on posts/pages because the way I've implemented it would break any existing bigimgs on posts/pages.
