### ISSUE TITLE
Posts missing from front page?

### ISSUE THREAD

**Issue by hwchen** [halogenica/beautifulhugo#150]
Hello,

Sorry if I'm missing something really obvious, but on first usage of the theme, no new posts show up on the front page. I can access them through the tags page if I add tags to the front matter of the post.

I've simply copied over the example site config.toml for testing purposes and then tried to make a few test posts. Everything else works except that no post listing shows up on the home page.

Thanks for any help!

(Using Hugo 0.37.1 and the beautifulhugo theme I cloned today)

**Comment by mominul** [comment]
I think I also faced the same issue. I solved the issue by adding this line to frontmatter to every posts:
```yaml
type: post
```

**Comment by yogster** [comment]
Make sure your posts are under `/content/post` **(in singular)** instead of `/content/posts`. It took me ages to figure that out when I started using Hugo.

**Comment by hwchen** [comment]
So, after trying out some other themes, I realized that many themes change the directory where they search for posts. I've seen `post`, `posts`, and `blog`.

Would have been nice if there was some way to have an error message so that I wouldn't have had to spend so much time debugging.

Anyways, thanks for the tips!

**Comment by ventz** [comment]
@hwchen  It seems that `posts` is the official directory structure in hugo
(see official tutorial: https://gohugo.io/getting-started/quick-start/)

@halogenica Would it be possible to to standardize on "posts"?
