### ISSUE TITLE
Use equations in blogdown in rmarkdown post

### ISSUE THREAD

**Issue by MislavSag** [halogenica/beautifulhugo#151]
I want to use equations in Rmd document, that represents post in blogdown blog. When I use common approach for equations in rmarkdown:

` $BDP = \sum S + \sum K + \sum D + \sum R + \sum A + \sum P$`

it doesn't show equation on a blog (web page). Equation is displayed as:

`\(BDP = \sum TroškoviRada + \sum Kamate + \sum Dividende + \sum Rente + \sum Amortizacija + \sum Profit\)`

Why blog that is created using blogdown package doesn't "recognize" equation?

**Comment by halogenica** [comment]
I don't think this has anything to do with this theme, and is more a question for hugo itself.
