### ISSUE TITLE
Mastodon social icon

### ISSUE THREAD

**Issue by yogster** [halogenica/beautifulhugo#152]
Hi! I have opened a [Mastodon](https://mastodon.social) account and want to display a link to it in my blog, but there is no mastodon option available in the config.toml.

This is an easy enough change, so I would be happy to do a PR with it if @halogenica you consider it appropriate?

If so, [FontAwesome doesn't have a mastodon icon](https://github.com/FortAwesome/Font-Awesome/issues/10897) and haven't actually accepted new icon PRs since October 2016. Would it be OK to use [ForkAwesome](https://github.com/ForkAwesome/Fork-Awesome/) instead?

And hey - Thanks for the great work!

**Comment by halogenica** [comment]
Hello, I updated FontAwesome recently and it now has a social icon for Mastadon. But I'm unsure of what the appropriate link and "username" fields should be for this service. Would you mind making a PR? I'd be happy to integrate it. Thank you!
