### ISSUE TITLE
Allow for scrollable code blocks

### ISSUE THREAD

**Issue by madsolar8582** [halogenica/beautifulhugo#166]
When posting content with code blocks that contain long lines (e.g. Objective-C code), the generated code blocks on the page do not allow the user to scroll. This can lead to weird spacing issues and can cut off code to make it not syntactically valid. Therefore, please update the code blocks to allow for scrolling similar to how GitHub does it.

Example:
```obj-c
- (void)someTest
{
  NSPredicate *predicate = [NSPredicate predicateWithBlock:^BOOL(id _Nullable object, NSDictionary<NSString *,id> *_Nullable bindings) {
    // Perform logical validation
  }];

  XCTNSPredicateExpectation *expectation = [[XCTNSPredicateExpectation alloc] initWithPredicate:predicate object:someObject];
  
  [someObject doWork];

  [self waitForExpectations:@[expectation] timeout:2];
}
```

**Comment by halogenica** [comment]
Thanks for the suggestion, I think this works now! If not, please let me know.

**Comment by jklaise** [comment]
@halogenica I'm struggling to make the code blocks scrollable with the latest version, the code just cuts off at the edge of the block. I'm sure this worked in an earlier version (circa May last year in contrast to @madsolar8582 ).
