### ISSUE TITLE
Summary text optionally instead of truncated body text?

### ISSUE THREAD

**Issue by fubarhouse** [halogenica/beautifulhugo#171]
In attempting to display alternative content on the homepage, I've noticed there's little control over influencing what is shown on the homepage.

I'd like to request for an optional summary field on posts to be able to provide alternative text explicitly as needed on the homepage.

Otherwise I'm loving the theme. 👍

**Comment by halogenica** [comment]
Thanks for the request! Addressed here: 65cdb2e82d2ce73b44c51d1d06a64db6a4a7d134
