### ISSUE TITLE
I want #mytag lowercase and preceded by # everywhere, including in <title> tag

### ISSUE THREAD

**Issue by nancym** [halogenica/beautifulhugo#172]
First, thank you for this theme, which will soon (I hope!) be in use on my updated web site!

On each tag page, there is an inconsistency that I've spent a long time trying to solve. For example, look at [themes.gohugo.io/theme/beautifulhugo/tags/math/](https://themes.gohugo.io/theme/beautifulhugo/tags/math/) and you will see:

1. The `<title>`, which is displayed in the browser tab, is **Math**
2. The `<h1>`, which is displayed on the page under the GitHub logo, is **#Math**
3. The `<div class="blog-tags">`, which is displayed under the post excerpt, is **#math**

On my site, I'd like all three of these to be **#math**, i.e., all lowercase and preceded by **#**.

I solved 2 by editing `\layouts\_default\list.html` and changing this:

```html
 <h1>{{ if .Data.Singular }}#{{ end }}{{ .Title }}</h1>
````
to this (along with some cleanup, which I won't post):

```html
{{ if .Data.Singular }}
     <h1 style="text-transform:lowercase;">#{{ .Title }}</h1>
```

My question to you all is what is a good way to solve 1? I have tried a lot of things and keep blowing up my Hugo builds because I don't really understand Go templates and Go coding. I'd really appreciate any tips.

Thank you!

**Comment by halogenica** [comment]
Thanks for the comment! This issue is quite old and the theme doesn't quite look this way anymore. Hopefully you've found a solution that works for you :)
