### ISSUE TITLE
Invalid markup (head/body tags)

### ISSUE THREAD

**Issue by max-arnold** [halogenica/beautifulhugo#176]
It looks like head/body tags are misplaced:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fthemes.gohugo.io%2Ftheme%2Fbeautifulhugo%2F

Original Jekyll theme has no such issues.

**Comment by halogenica** [comment]
This should be fixed, as well as many other html errors caught by the validator. Thank you for the bug! If you see more errors please let me know.
