### ISSUE TITLE
Align Equations KaTeX+Markdown

### ISSUE THREAD

**Issue by TheGoodMath** [halogenica/beautifulhugo#183]
Hello,

I've really tried to figured out a way to align equations.

This is what I would like to render : 
Aligning Equations with Comments
http://www.math.mcgill.ca/yyang/regression/RMarkdown/example.html (last example)

This is the code : 
```
$$
\begin{align}
    3+x &=4 && \text{(Solve for} x \text{.)}\\
    x &=4-3 && \text{(Subtract 3 from both sides.)}\\
    x &=1   && \text{(Yielding the solution.)}
\end{align}
$$
```
(end when I copy/post this code, it doesn't render it properly)

What is the code that would render an align equation with comments?

Thank you!

**Comment by ImAlexisSaez** [comment]
Take a look at [https://khan.github.io/KaTeX/function-support.html#environments](https://khan.github.io/KaTeX/function-support.html#environments), maybe you want to try `aligned` instead of `align`.

Besides, I usually have to escape the `\` and write `\\\\` instead of `\\`.

**Comment by TheGoodMath** [comment]
1. This
`
$$
\begin{aligned}
   a&=b+c \\
   d+e&=f
\end{aligned}
$$
`
renders
![1](https://user-images.githubusercontent.com/40063434/43044614-a11d0ba6-8da9-11e8-8536-d51bc6a048e0.PNG).

2. This
`
$$
\begin{aligned}
   a&=b+c \\\\
   d+e&=f
\end{aligned}
$$
`
render
![2](https://user-images.githubusercontent.com/40063434/43044673-0f1b850a-8dab-11e8-8281-c380e1b18a38.PNG)

3. This
`
$$
begin{aligned}
   a&=b+c \\
   d+e&=f
end{aligned}
$$
`
renders
![3](https://user-images.githubusercontent.com/40063434/43044840-31732128-8dae-11e8-92fc-4b6b7db2836e.PNG)


4. This
`
$$
\begin{aligned}
   a&=b+c \\\\
   d+e&=f
\end{aligned}
$$
`
renders
![4](https://user-images.githubusercontent.com/40063434/43044748-c95fb3cc-8dac-11e8-80ae-9949fa1a816d.PNG)

5. This
`
$$
begin{aligned}
   a&=b+c \\
   d+e&=f
end{aligned}
$$
`
renders
![5](https://user-images.githubusercontent.com/40063434/43044766-097c8d22-8dad-11e8-842e-aa6026e45407.PNG)

6. This
`
$$
begin{aligned}
   a&=b+c \\\\
   d+e&=f
end{aligned}
$$
`
renders
![6](https://user-images.githubusercontent.com/40063434/43044807-9cd3dd5a-8dad-11e8-81a0-811147111ffc.PNG)

7. This
`$$
begin{aligned}
   a&=b+c \\\\
   d+e&=f
end{aligned}
$$
`
renders
![7](https://user-images.githubusercontent.com/40063434/43044819-db213ae4-8dad-11e8-90ae-35f550502634.PNG)

8. This
`
$$
begin{aligned}
   a&=b+c \\
   d+e&=f
end{aligned}
$$
`
renders
![8](https://user-images.githubusercontent.com/40063434/43044833-0847b6f6-8dae-11e8-9b96-b107c76557dc.PNG)


What else can I try?

**Comment by TheGoodMath** [comment]
So far, I'm starting to get somewhere :)
The trick is to write everything on one line which is not really convenient.
This
`
test

$$\begin{aligned} A & = B \\\\ & = C \end{aligned}$$
`
renders
![capture](https://user-images.githubusercontent.com/40063434/43048279-33386842-8de5-11e8-83f1-6fbfd818909e.PNG)

I would like to have the equations align on the left.

**Comment by ImAlexisSaez** [comment]
> The trick is to write everything on one line which is not really convenient.

Yeah, it isn't convenient at all. I wrote a post about determinants ([here](https://imalexissaez.github.io/2018/07/16/mezclando-determinantes-y-numeros-combinatorios/)) a few days ago and it was a little nightmare.

To align equations differently maybe you'll have to play with CSS.

**Comment by halogenica** [comment]
Did anyone figure this out in a more convenient way? I assume this is mostly a KaTeX thing, but if there's specific CSS that should be integrated into the theme to make this better please send me a PR and I'd be happy to merge it. Closing this for now since I don't see anything specific to implement.

**Comment by jklaise** [comment]
@TheGoodMath writing everything on one line does not work for me, everything gets rendered in one line.

**Comment by rikhuijzer** [comment]
For me it also worked on one line as stated by @jklaise, which was pretty unreadable. Improved it by using `replaceRE`. For example, in `content.html`:
```
{{ .Content | replaceRE "\\\\nl" "\\\\" | safeHTML }}
```
now, in a Markdown file, I can write
```
$$
\begin{aligned}
  a&=b+c \nl
  d+e&=f
\end{aligned}
$$
```
and KaTeX renders it correctly since the newline is removed.
By the way, I don't know exactly why newlines are now removed.
It also works on
```
foo \nl
bar
```
which in the output becomes
```
foo \\ bar
```
