### ISSUE TITLE
delete social icons when inside a post and disable preview on a post

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [halogenica/beautifulhugo#190]
how can i delete the social icons when i am reading a post?
and how can i disable the preview post? i only want to see the text when i pressed the title

**Comment by barcoak1** [comment]
Find footer.html file and remove something like this
<span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-rss fa-stack-1x fa-inverse"></i>

**Comment by BrunoTeixeira1996** [comment]
what do you mean? i figure out how would i delete the share icons by only changing the argument do False
but now  i want to create a post with only the title. when i press that tittle the text and images appear but instead when i create a post it appears the title, the text and the image

**Comment by BrunoTeixeira1996** [comment]
same as me. right know i am at work with my laptop but if you can test that would be great, anyways in a few hours ill be at home and i can say if it works

**Comment by BrunoTeixeira1996** [comment]
in about title it appears with a 's' like "abouts" and i check the code xD, dunno what is happening

**Comment by BrunoTeixeira1996** [comment]
so i found how to stop preview. just delete this {{ partial "post_meta.html" . }}
              <div class="post-entry">
                {{ if .Truncated }}
                  {{ .Summary }}
                  <a href="{{ .Permalink }}" class="post-read-more">[{{ i18n "readMore" }}]</a>
                {{ else }}
                  {{ .Content }}
                {{ end }}
              </div>

in index,html but i am still trying to understand why there's an 's' in about page
