### ISSUE TITLE
Add support for big images

### ISSUE THREAD

**Issue by daattali** [halogenica/beautifulhugo#2]
See https://github.com/daattali/beautiful-jekyll/commit/e6cb0a4f546d43f2c121970ac181c0d12ab1242c , you could copy exactly the same code

This will allow you to have a wide image in the header of a page

**Comment by halogenica** [comment]
Thanks for the heads up! Just fixed. See: https://github.com/halogenica/beautifulhugo/commit/87adc9d6913dcc4cf6cb8da22cb3773c186422be
