### ISSUE TITLE
[bug] RSS icon always show

### ISSUE THREAD

**Issue by hukacode** [halogenica/beautifulhugo#21]
Hello,

RSS icon always show (and wrong link) although I did not set it

**Comment by halogenica** [comment]
RSS feeds were not configurable. I added them with the following change: 50fad43b1fb10fa763340f3fd8e537c6d45e08aa

I don't know what you mean by it has the wrong link. The link always works for me (should take you to an index.xml file) and I was able to subscribe to it with an rss reader and view all the posts, etc.

**Comment by hukacode** [comment]
Hi @halogenica,

Thank you for your response.

Can you go to my link?
hukacode.com
https://github.com/hukacode/huka-blog/blob/master/config.toml

I'm sorry, my English is not good. So I can't explain details.

**Comment by halogenica** [comment]
No problem. I just added the ability to disable RSS feeds for you this morning, so you have to get the latest version beautifulhugo :) Just get the latest version, and compare with the config.toml in the example site. Under the [Params] section at the top, there's a field called "rss = true". If you want to disable RSS, just change this to "rss = false". Again, you have to have the latest version of the theme downloaded for this to work.

**Comment by hukacode** [comment]
Hi @halogenica 

It's work like a charm. Thank you for helping me!
