### ISSUE TITLE
Navbar obscures heading

### ISSUE THREAD

**Issue by bitfield** [halogenica/beautifulhugo#212]
With a fresh install of Beautiful Hugo on Hugo 0.50, the front page looks like this:

![screen shot 2018-11-02 at 16 33 08](https://user-images.githubusercontent.com/142262/47928223-781aaf00-debd-11e8-9515-e3516d7e4583.png)

**Comment by halogenica** [comment]
I can't reproduce this, but I think I know what's wrong. It looks like there's a few styles that are incorrect in the screenshot you shared above; have you tried clearing your browser cache, etc? The fonts are incorrect, the social share buttons are the wrong color, the webpage title isn't centered, etc.

**Comment by bitfield** [comment]
How strange! On restarting Hugo, everything is fine. I tried to reproduce this by creating a new site and setting the theme, but I don't see the same problem. I did try a couple of other themes before this one, so possibly some assets from one of those themes were cached and that was causing the layout problems. Thanks for the help!
