### ISSUE TITLE
controling size of logo image

### ISSUE THREAD

**Issue by rickysarraf** [halogenica/beautifulhugo#213]
First, thank you so much for this awesome and elegant theme for hugo.

Most of the stuff is quick to enable and make use of. The only problem I have run into is is with the logo.
I made the following changes:

```
[Params]
  homeTitle = "RESEARCHUT" # Set a different text for the header on the home page
  logo = "/sites/default/files/researchut_large.png"
  #logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
```

The problem is with the way the logo is rendered. The size of the image rendered is very small in comparison to its origian size. The actual size of the logo is: `content/sites/default/files/researchut_large.png: PNG image data, 448 x 216, 8-bit/color RGBA, non-interlaced`. But the rendering gets it to around a very tiny size.

The below screenshots may give a better picture of the problem.

![screenshot_20181105_220156](https://user-images.githubusercontent.com/65480/48010995-bb3a8380-e144-11e8-874e-9654c0547784.png)
![screenshot_20181105_220249](https://user-images.githubusercontent.com/65480/48010996-bbd31a00-e144-11e8-8a8c-9987ea67d943.png)

**Comment by halogenica** [comment]
Submitted here: 6cf90512e9e2fd69abb655cb52b2e075eabcedaf

Thank you :)
