### ISSUE TITLE
[new-feature] Search, formspree

### ISSUE THREAD

**Issue by hukacode** [halogenica/beautifulhugo#22]
Hello,

I don't know how to add Search and Formspree/ Can you help me, please?
Thanks in advance!

**Comment by halogenica** [comment]
The best place to research this is likely the hugo forums (https://discuss.gohugo.io/). If you add support for search and formspree I would be glad to review and accept a pull request :)

**Comment by hukacode** [comment]
Hi @halogenica,

I got it. Thank you so much!
