### ISSUE TITLE
Google analytics not working at all

### ISSUE THREAD

**Issue by berbers** [halogenica/beautifulhugo#247]
I installed this theme for my blog and set my Google Analytics ID number correctly (this ID worked perfectly well with other themes). But I see no statistics on my Google Analytics anymore.

I did not modify the code of any page of the theme, except the configuration file to add my ID there.

How do you fix this?

**Comment by berbers** [comment]
my ID was wrong, sorry

**Comment by backpack5689** [comment]
@SebsL, what ID do you put? Is it your Measurement ID, or is it your Stream ID?
