### ISSUE TITLE
Error processing shortcode _internal/shortcodes/highlight.html

### ISSUE THREAD

**Issue by senthilthyagarajan** [halogenica/beautifulhugo#28]
In a post when I use a highlight javascript to insert a code  it throws the following error while building:

`error processing shortcode _internal/shortcodes/highlight.html`

**Comment by halogenica** [comment]
Do you have python and pygments installed? Are you able to use the highlight shortcode when using a different theme without error? there is nothing in this theme that should do anything special with the highlight shortcode.
