### ISSUE TITLE
Thanks so much for the theme, check out my dark version

### ISSUE THREAD

**Issue by fgimian** [halogenica/beautifulhugo#3]
Hey there, thanks so much for your work on this theme :smile: 

I've further customised the CSS heavily and made a dark theme with Solarized Dark (ported from Octopress) for code blocks.

Thought you might want to give it a quick look: http://fgimian.github.io/

Please note that I'm colourblind, so forgive me if there are any bad colour choices :smile: 

Also, is there any easy way to make the width of posts wider?  e.g. on a regular post [like this one](http://fgimian.github.io/blog/2014/04/27/running-nose-tests-with-plugins-using-the-setuptools-test-command/).

Any feedback is welcome
Fotis

**Comment by halogenica** [comment]
Oh cool! Thanks for the link to your customized version of the theme. I especially like the way the code snippet blocks look. 

To modify the width, I believe the correct thing to do is modify the CSS classes that look like the following:
<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

So for example to make the content in that link you sent me wider, you probably want to change "col-lg-8" to "col-lg-10" or something larger so it spans more columns, and then adjust the offset/padding accordingly.
