### ISSUE TITLE
Hugo 0.57.0 breaks index/homepage (only Posts shown)

### ISSUE THREAD

**Issue by bobek** [halogenica/beautifulhugo#300]
Index page will only contain "Posts" link when built with hugo `v0.57.0`. It is caused by change of semantics of `.Pages` as noted on the release notes - https://github.com/gohugoio/hugo/releases/tag/v0.57.0

Fix is simple as bobek/beautifulhugo@79abb2e . But that is not backwards compatible.

**Comment by bobek** [comment]
> Index page will only contain "Posts" link when built with hugo `v0.57.0`. It is caused by change of semantics of `.Pages` as noted on the release notes - https://github.com/gohugoio/hugo/releases/tag/v0.57.0
> 
> Fix is simple as [bobek/beautifulhugo@79abb2e](https://github.com/bobek/beautifulhugo/commit/79abb2e) . But that is not backwards compatible.

**Comment by bobek** [comment]
I have just verified that `0.54.0` actually works with the patch as `RegularPages` collection was added long time ago (I have found them even in version `0.18.0` but version from last year don't work for other various reasons (e.g. partials)). So maybe this patch is actually acceptable as is.

**Comment by henryiii** [comment]
I've found the same things and committed the exact same page independently. I highly recommend this gets merged!

**Comment by mckmonster** [comment]
I did a pull request for that #302

**Comment by halogenica** [comment]
This should now be fixed with https://github.com/halogenica/beautifulhugo/commit/1d75ccd689fd52f394077f5a5e4c88ca580a07bf - thank you for the report!
