### ISSUE TITLE
Missing div on 'tags' page

### ISSUE THREAD

**Issue by kosmoz** [halogenica/beautifulhugo#33]
The previews on a `localhost:1313/tags/sometag` page are wider than most other pages since they are not wrapped in a 

    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1"></div>

Is this intentional? To me it looks inconsistent.

I can try to fix it, though I'm not very familiar with Go's template syntax.

**Comment by halogenica** [comment]
Thanks for pointing that out! It wasn't intentional. Fixed with this change: bb64fb5b8e7634294a06ad76f32d876f3009ee41

**Comment by kosmoz** [comment]
Wow, that was quick! Thx :-)
