### ISSUE TITLE
bump jquery version in partials/footer file

### ISSUE THREAD

**Issue by nidhi-wgl** [halogenica/beautifulhugo#342]
I saw it is loading 1.12.4 which is from 2016 and has Vulnerabilities. 

Is the JQuery library anywhere used? is it used in staticman? if not remove it or load only when staticman enabled?

**Comment by iaeiou** [comment]
Nice spot, Jquery<3.5.1 is [reported as vulnerable to XSS](https://snyk.io/vuln/search?q=jquery&type=any). It's used in BeautifulHugo at least for the `/tags` page.

If you want to update to the last version, you can
- download it [from the official website](https://jquery.com/download/)
- rename and move this file to `/static/jquery.min.js`
- setup BeautifulHugo to use local files with the following parameter in `config.toml`:

```
[Params]
selfHosted = true
```

**Comment by VincentTam** [comment]
Hi, this is the contributor for Beautiful Jekyll's Staticman integration.  Beautiful Hugo is a theme derived from Beautiful Jekyll.  I've contributed to both themes.  <span>@</span>daattali, the author of Beautiful Jekyll, has switched to an up-to-date version of jQuery slim (despite ).  That motivated me to follow suit for this theme.
