### ISSUE TITLE
Is this project unmaintained?

### ISSUE THREAD

**Issue by vdot0x23** [halogenica/beautifulhugo#357]

**Comment by KetanIP** [comment]
Maybe. Last commit is 11 months old.

**Comment by halogenica** [comment]
I’m sorry about that, it’s just very slow going. This year has been tough. I do plan to do a bunch of cleanup and accept a bunch of PRs once or twice a year, I just haven’t gotten to it yet this year. 

So, not dead, just very slow. If you keep submitting PRs I will eventually merge them :)
