### ISSUE TITLE
Posted date is showing as `Posted on map[Count:January 23, 2021]`

### ISSUE THREAD

**Issue by joncol** [halogenica/beautifulhugo#376]
This happens only when I deploy via Netlify. When running `hugo server` locally, everything looks fine. But when looking at the source of the deployed page, the date is instead this weird `map[Count:...]`. Any idea of what I could try? I really like the theme otherwise.

![image](https://user-images.githubusercontent.com/194062/105614994-6ccd3a00-5dcd-11eb-83f9-eaf2b40a72e5.png)

**Comment by iaeiou** [comment]
Hi,

You can find information about this issue there: https://github.com/halogenica/beautifulhugo/pull/361

**Comment by joncol** [comment]
Thanks for pointing me in that direction.
