### ISSUE TITLE
Duplicated title

### ISSUE THREAD

**Issue by alienbogart** [halogenica/beautifulhugo#397]
Right now, on the main page, beautifulhugo sets the title as "Page Title - Page Title". I wish to avoid the repetition. How can I do that?

**Comment by whatacold** [comment]
I can confirm this, I find the `<title>` code at `head.html` but don't know how to fix it yet.

**Comment by RoneoOrg** [comment]
In `layout/partials/head.html`, replace

```
<!-- Site Title, Description, Author, and Favicon -->
{{- with ($.Scratch.Get "Title") }}
  <title>{{ . }} - {{ $.Site.Title }}</title>
{{- end }}
```

with

```
<!-- Site Title, Description, Author, and Favicon -->
  {{ if .IsHome }}
    {{- with ($.Scratch.Get "Title") }}
      <title>{{ . }}</title>
    {{- end }}
  {{ else }}
    {{- with ($.Scratch.Get "Title") }}
      <title>{{ . }} - {{ $.Site.Title }}</title>
    {{- end }}
  {{ end }}
```

This should normally do the trick

**Comment by RoneoOrg** [comment]
A pull request is now pending for review: https://github.com/halogenica/beautifulhugo/pull/398
