### ISSUE TITLE
House posts on arbitrary page

### ISSUE THREAD

**Issue by stockphrase** [halogenica/beautifulhugo#407]
Is it possible to make the posts appear on an arbitrary page, rather than the home page using the `mainSections` parameter?

**Comment by ibnunowshad** [comment]
Comment out post section in *index.html* and add your Homepage content in *content* folder as *_index.md*

index.html
```{{ define "main" }}
  <div role="main" class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        {{ with .Content }}
          <div class="well">
            {{.}}
          </div>
        {{ end }}
        <!--
        <div class="posts-list">
          {{ $pag := .Paginate (where site.RegularPages "Type" "in" site.Params.mainSections) }}
          {{ range $pag.Pages }}
            {{ partial "post_preview" . }}
          {{ end }}
        </div>

        {{ if or (.Paginator.HasPrev) (.Paginator.HasNext) }}
          <ul class="pager main-pager">
            {{ if .Paginator.HasPrev }}
              <li class="previous">
                <a href="{{ .Permalink }}page/{{ .Paginator.Prev.PageNumber }}/">&larr; {{ i18n "newerPosts" }}</a>
              </li>
            {{ end }}
            {{ if .Paginator.HasNext }}
              <li class="next">
                <a href="{{ .Permalink }}page/{{ .Paginator.Next.PageNumber }}/">{{ i18n "olderPosts" }} &rarr;</a>
              </li>
            {{ end }}
          </ul>
        {{ end }} -->
      </div>
    </div>
  </div>
{{ end }}
```


_index.md
```
---
title: ""
#subtitle: Homepage subtitle bypass
type: "page"
#layout: "list"
showthedate: false
comments: false
---
```

**Comment by stockphrase** [comment]
Hi. Thanks for this. I was able to get the posts to appear on a page called 'posts' now. However, for some reason this fix prevents the title of the page from appearing as normal. The page title is small and left justified. What am I doing wrong here?
![Screenshot from 2021-07-27 17-49-06](https://user-images.githubusercontent.com/2568776/127232119-26751d7d-3f77-4dd9-9cb0-1ad48334a296.png)

**Comment by ibnunowshad** [comment]
Kindly add *_index.md* under post folder inside content as below, it will solve the left justified page title to center justified. Comment out what section you do not need there. I give the sample code from site, they were not merged it to this repo.
```
---
title: Posts
#subtitle: Posts
type: "page"
#layout: "list"
showthedate: false
comments: false
---
```

**Comment by stockphrase** [comment]
Perfect! Thank you, Mohamed.
