### ISSUE TITLE
Big image on Home page

### ISSUE THREAD

**Issue by juchopin** [halogenica/beautifulhugo#413]
I was wondering how I could add a big image to the home page. I guess I should edit the custom_head file but I really don't know how to do it.

Thanks for your help

**Comment by juchopin** [comment]
I found the answer! I just uncommented the corresponding lines ([[Params.bigimg]]) in the config file.

**Comment by RoneoOrg** [comment]
Hi @juchopin,
if your problem is fixed, could you please close this issue?
