### ISSUE TITLE
Is this theme still being maintained?

### ISSUE THREAD

**Issue by AjayKMehta** [halogenica/beautifulhugo#431]
Firstly, I appreciate all the work done by @halogenica and other contributors and realize that OSS is a labor of love that people work on in their spare time. 

I want to know if this is still being actively maintained because there are 60 PRs open and the last PR was merged over a year ago.

**Comment by RoneoOrg** [comment]
Good news here:

- halogenica reappeared and merged several PR ❤️
- I've been granted the right to pull to this repo by halogenica, and other co-maintainers may have been invited too! ✨

Here is my plan:

- [x] Get in touch with halogenica to discuss a roadmap and agree on common practices (✅ Done today)
- [ ] Answer and sort issues + PR
- [ ] Discuss a roadmap
- [ ] Publish a status update about BH and a call for contributions
- [ ] Promote BH on [Jamstack.club](https://jamstack.club/), [discourse.gohugo.io](https://discourse.gohugo.io/), and a couple of slack channels about Hugo/Jamstack stuff
- [ ] Get more contributors on board
- [ ] Maintain a presence here and answer basic users' questions
