### ISSUE TITLE
Make the Gitlab icon link more general

### ISSUE THREAD

**Issue by stafusa** [halogenica/beautifulhugo#436]
One nice advantage of gitlab, compared to github, is the possibility of hosting it somewhere else than gitlab.com, but right now in beautifulhugo you can't link the social icon to any other instance of gitlab.

**Suggestion**  
To make it possible, in the theme file `themes/beautifulhugo/data/beautifulhugo/social.toml`, for the base gitlab URL to be different from the default `https://gitlab.com/`, in order to permit linking to instances hosted elsewhere. The simplest way to achieve this is probably by changing `url = "https://gitlab.com/%s"` to `url = "%s"`. Leaving it to the user to provide the full URL.

It's rather easy to implement and would be a welcome improvement.

**Comment by RoneoOrg** [comment]
Good idea! Would you like to submit a PR @stafusa ?

**Comment by stafusa** [comment]
Yes, I can give it a try. @RoneoOrg 

Can I create a branch here or should I do it from a fork?

**Comment by RoneoOrg** [comment]
> Yes, I can give it a try.

Great!

> Can I create a branch here or should I do it from a fork?

You have to use a fork

**Comment by stafusa** [comment]
@RoneoOrg  There it is: Two lines. :-) I guess it'll be easy to review.
