### ISSUE TITLE
Internationalise the theme

### ISSUE THREAD

**Issue by rayjolt** [halogenica/beautifulhugo#44]
It would be nice for Beautiful Hugo to be available in different languages. At the moment, only people writing in English have access to this wonderful theme. Doing i18n would involve a few different things:

1. Move all English text in the templates to i18n/en.yaml and reference it with `{{ i18n }}`
2. Alter URLs in the templates to be language-relative
3. Alter `lang` attributes in the templates to use the correct language
4. Add a language switcher to the navbar
5. Add links to translated content in posts, and maybe in pages

The first three are not so hard, but 4 and 5 require some design thought. I think the language selector could be implemented as a multi-level menu at the top-right, or if there are only two languages, a menu link displaying the name of the other language. The links to translations of posts could maybe go to the right of the hashtags. But I'm open to suggestions.

I have already done some of this work for my personal site, so if this looks like a good idea I can start adapting my work for use in this repo.

**Comment by halogenica** [comment]
I would certainly welcome the feature! I honestly don't know exactly what this would look like. I see you forked this repo, so if you create a branch in yours that supports international languages I'd like to follow along with what changes are necessary. 

I'm mildly concerned about the bugs that may arise by supporting such a feature because I'm not capable of testing it. I already get daily requests which isn't a sustainable cadence for me; but of course once I add all the features and they're all perfect, my issues count will drop to zero... right? :)

**Comment by rayjolt** [comment]
Ok, I'll add the features in my repo when I get a chance. You don't need to be able to speak any other languages to test i18n, by the way. It's pretty much just a matter of checking that text appears where it should, and appears in the right language, and that all the links work properly. I'll maybe put together an example multilingual site as well so that you can just clone that, then clone the theme, then start testing with `hugo server -t beautifulhugo`.

**Comment by halogenica** [comment]
That would be great, thank you!

**Comment by rayjolt** [comment]
Ok, I've finished coding this up now. You can see the i18n code at the [i18n branch on my fork](https://github.com/rayjolt/beautifulhugo/tree/i18n), and I've created an example multilingual site at [rayjolt/hugo-multilingual-example](https://github.com/rayjolt/hugo-multilingual-example).

You'll need to tweak the config etc. for things specific to beautifulhugo like the avatar and the footer icons. (Maybe we can have a new example multilingual site in the beautifulhugo source tree that has these things in? Let me know what you think.)

There isn't any support for RTL languages yet, but that can always come later.

**Comment by halogenica** [comment]
Yeah I'd love the ability to have a multilingual example site. Even if the posts aren't entirely written in another language, at least demonstrating the ability to change the locale in the config.toml to switch to another language in the hardcoded text.
