### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by Ianneee** [halogenica/beautifulhugo#441]
Thanks for the theme is very nice. 
I would like to ask you which cookies should I add to my cookies policy using this theme for my site? 
Thank you

**Comment by RoneoOrg** [comment]
Hi,

no cookies are used by this theme, but default settings use remote services like `google fonts` or `jsdelivr`

This can be avoided with the following param in `config.toml`:

```
[Params]
  selfHosted = true
```
Note the following reports:

- https://github.com/halogenica/beautifulhugo/issues/393
- https://github.com/halogenica/beautifulhugo/issues/392

**Comment by RoneoOrg** [comment]
I'm closing, please reopen if additional info are required
