### ISSUE TITLE
Document the feature `selfHosted`

### ISSUE THREAD

**Issue by RoneoOrg** [halogenica/beautifulhugo#446]
With default settings, visiting to a website using Beautifulhugo connects also to remote services like `google fonts` or `jsdelivr`

This can be avoided with the following param in config.toml:

```
[Params]
  selfHosted = true
```

Note the following reports:

- https://github.com/halogenica/beautifulhugo/issues/393
- https://github.com/halogenica/beautifulhugo/issues/392

**Comment by marcogabriel** [comment]
Thanks for mentioning the `selfHosted` setting - that was exactly what I was looking for. I created a PR to README.md - maybe it get's integrated so that other people looking for that feature won't need to check issues first :-).
