### ISSUE TITLE
Copyright Year in Footer Shows As "© 0001"

### ISSUE THREAD

**Issue by dwayneem** [halogenica/beautifulhugo#452]
The copyright year in the footer of the generated site is shown as "© 0001". How do I set the copyright year? (Yes, I know I could edit the generated HTML.)

![2022-12-25_08-29-51](https://user-images.githubusercontent.com/22521217/209469896-8e69c587-d60c-4082-a302-c3edff521604.png)

macOS 13.1
Hugo v0.109.0

**Comment by dwayneem** [comment]
Okay, after I added my first post, the copyright year was set correctly.

**Comment by AIGeneratedUsername** [comment]
If anyone will come here with the same problem: make sure that your single post had a date in the past (not in the future).
