### ISSUE TITLE
Font awesome 4.5 upgrade

### ISSUE THREAD

**Issue by xor-gate** [halogenica/beautifulhugo#5]
Hi, 

I added myself wikipedia and soundcloud glyphicons, only the wikipedia-w glyph is available in font awesome 4.4 or higher. I noted the upstream author of the beautiful-jekyll theme and he fixed it. Maybe you also would like it. Adding wikipedia and soundcloud profiles with config.toml would also be usefull for other people. See the issue for more details (the extra footer info is also there pasted):

 https://github.com/daattali/beautiful-jekyll/issues/50

Thanks for your time and effort to have this theme ported to Hugo!

Kind regards,
Jerry

**Comment by halogenica** [comment]
Very cool! Thanks a lot for the added feature, I'm happy to update the theme. Made a checkin at https://github.com/halogenica/beautifulhugo/commit/ecb7e949e7c08d982d77b16be53e89e7202f5ae6 that should add everything.

**Comment by xor-gate** [comment]
Great you like it :+1:
