### ISSUE TITLE
.Site.IsServer was deprecated

### ISSUE THREAD

**Issue by hugo-mcfrojd** [halogenica/beautifulhugo#501]
Im using your theme as a git submodule.

When i render the website Hugo says:
"deprecated: .Site.IsServer was deprecated in Hugo v0.120.0 and will be removed in a future release. Use hugo.IsServer instead."

The only place i can find the use of ".Site.IsServer" is in your theme in "layouts/partials/head.html" where line 100 says
`{{- if not .Site.IsServer -}}`

Do you have plans to to change this deprecated code to the new one?

I am not tech savvy enough to make a pull request.

**Comment by hydr0nium** [comment]
@hugo-mcfrojd There doesn't seem to be much activity on the pull requests. Despite that I can put up a pull request in the next couple of days with a fix for that 😄

**Comment by hydr0nium** [comment]
I just put up a pull request that fixes that issues #502

**Comment by henryiii** [comment]
I can merge stuff if poked enough. :)
