### ISSUE TITLE
Tag support

### ISSUE THREAD

**Issue by juanrodriguezmonti** [halogenica/beautifulhugo#6]
Hi! Thanks for your theme! It is amazing! I would like to know if your theme supports basic tags ? Or, if it is gonna be supported in some near future.

Thanks!
Juan

**Comment by jossemarGT** [comment]
I couldn't find anything in hugo documentation but it looks doable, [hugo slim](https://github.com/zhe/hugo-theme-slim) already did it. I'd like to summit a PR copying that behavior, but it'll go at the end of my TODO stack. 

Happy coding :octocat:

**Comment by halogenica** [comment]
If someone would like to add tags I'd be happy to accept a pull request :) I will investigate them for a future theme and may add them to this one at that time.
