### ISSUE TITLE
Font Awesome Socialmedia Icons are not renderered

### ISSUE THREAD

**Issue by norbertfuhs** [halogenica/beautifulhugo#77]
Hi,

I wanted to use this awesome theme for my new blog but ran into the problem that the social media icons provided by Font Awesome arten renderendere strnge the RSS icon is rendered:
![bildschirmfoto 2017-07-11 um 16 55 47](https://user-images.githubusercontent.com/17197786/28074806-d3950340-6659-11e7-882c-d1734b02632d.png)

My config.toml looks something like this:

[Params]
author                 = "Norbert Fuhs"
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
email                  = "norbert.fuhs.xyz@gmail.com"
lang                   = "en"
pygmentsuseclasses     = false
rss                 = true
comments            = true

[Author]
name = "Norbert Fuhs"
email = "norbert.fuhs.xyz@gmail.com"
#facebook = "username"
#googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
github = "norberfuhs"
#gitlab = "username"
twitter = "@NorbertFuhs"
#reddit = "username"
#linkedin = "username"
#xing = "username"
#stackoverflow = "users/XXXXXXX/username"
#snapchat = "username"
#instagram = "username"
#youtube = "user/username" # or channel/channelname
#soundcloud = "username"
#spotify = "username"
#bandcamp = "username"
#itchio = "username"

I left the social.toml like in the sample..

When I do hugo server --theme=beautifulhugo --buildDrafts I only see the rss button rendered..

**Comment by halogenica** [comment]
I'm sorry to hear that! A few people have reported an issue with those icons, I think with Firefox specifically. I will have to investigate to see if I have some invalid HTML or if there is a known bug/workaround. What browser and what version are you using? Can you try another browser (just to help me debug). What version of Hugo? If you look at the page source, is the HTML present?

**Comment by norbertfuhs** [comment]
Hi, thanks for the quick response!

The html isn't present the page footer source with Safari Version 10.1.1 :
![bildschirmfoto 2017-07-11 um 17 33 14](https://user-images.githubusercontent.com/17197786/28076480-28aa3bac-665f-11e7-9c4e-9cc6d2f3f7d7.png)

I also tried Firefox 54.0.1 (64-Bit) with same result.

I'm using Hugo Static Site Generator v0.25 darwin/amd64 BuildDate: 2017-07-07T09:29:34+02:00

I hope this clears things up..

**Comment by ROYALBEFF** [comment]
Keep in mind that an ad-blocker can also be the reason. If you use an ad-blocker, try deactivating it.

**Comment by norbertfuhs** [comment]
Thanks for the hint but if an ad blocker would hiding it there should be html in the page source.. also I tried it in Firefox without ad-blocker stil the same... Safari has no ad blocker installed there is just nothing rendered I wonder if there is something wrong with my config.toml or social.toml file...

Anyway thanks for the help and hints so far!

**Comment by norbertfuhs** [comment]
Delete everything  cloned empty repo did git clone https://github.com/halogenica/beautifulhugo.git beautifulhugo again and rebuilt the whole site it now works even in Firefox... I have no idea why
![bildschirmfoto 2017-07-14 um 18 11 34](https://user-images.githubusercontent.com/17197786/28220496-f7bd7c30-68bf-11e7-90a8-02b79cd06f38.png)

Sorry for all the stress

**Comment by halogenica** [comment]
Bizarre! I'm really glad you figured it out!
