### ISSUE TITLE
use of GIT_COMMIT_SHA instead of `enableGitInfo = "true"`

### ISSUE THREAD

**Issue by dustymabe** [halogenica/beautifulhugo#82]
Hugo new user here.. Thanks for your theme. 

Just wondering why this theme uses [GIT_COMMIT_SHA](https://github.com/halogenica/beautifulhugo/blame/a9564d13d1eda78e87efdd6258b766ef0fb20fba/README.md#L56) environment variable instead of reusing information from hugo from [`enableGitInfo = "true"`](https://gohugo.io/variables/git/). There is probably something I'm missing. Thanks for your time to explain it.

**Comment by cite** [comment]
After trying this out, I can think of two possible explanations:

1. In `theme.toml`, the required `hugo` version is still `0.16`. If I'm not mistaken, this is the first version that supported `.GitInfo`, and it was still kind of flakey.
2. It's not the same data: The `.GitInfo` object is on a per-page base, while the solution using `GIT_COMMIT_SHA` looks at the whole repository.

CMIIW :-)

**Comment by dustymabe** [comment]
Thanks for the response

> In theme.toml, the required hugo version is still 0.16. If I'm not mistaken, this is the first version that supported .GitInfo, and it was still kind of flakey.

This is most likely the reason.

> It's not the same data: The .GitInfo object is on a per-page base, while the solution using GIT_COMMIT_SHA looks at the whole repository.

The `.Hash` value should be the same for every page. After all it is still a single git repository.

**Comment by cite** [comment]
> The .Hash value should be the same for every page. After all it is still a single git repository.

Yes, but it's still only for "real pages" - meaning it doesn't work when in a typical "blog style" setting, without `_index.md`, because the list of blog posts is not a page.

**Comment by halogenica** [comment]
I believe it should be GIT_COMMIT_SHA because it should be for the whole repository. Thanks for letting me know :)
