### ISSUE TITLE
Add custom main tile for home page

### ISSUE THREAD

**Issue by rootsongjc** [halogenica/beautifulhugo#90]
The home page main title is the same the website title, I think we should define a parameter in `config.toml` to custom the main title.

**Comment by petersendev** [comment]
I need this too (setting a custom text for the header on the home page), 
Will create a PR

**Comment by rsletta** [comment]
@halogenica - Can't this issue be closed, as a PR resolving it has been merged? 😊

**Comment by halogenica** [comment]
Thanks!
