### ISSUE TITLE
Chroma highlighting using pygmentOptions="linenos=table" bug?

### ISSUE THREAD

**Issue by joshuasheppard** [halogenica/beautifulhugo#97]
First, the theme is awesome. Thank you for it. And for the recent update to use Chroma.

When I switched over to Chroma today, I ran into a situation where when I use `pygmentOptions = "linenos=table"` in `config.toml` I see a vertical line artifact on the right hand side of any code that doesn't run the full width or trigger the horizontal scrollbars. 

Is there some other setting that I'm missing?

Hugo v0.30.2
beautifulhugo 7cdd0e0b3d986af12079c0f37d069fbe2713ab16
Chroma style monokai
Chrome browser

<img width="347" alt="2017-11-12_chroma-tables-bug" src="https://user-images.githubusercontent.com/1243348/32697242-027e906e-c752-11e7-81f3-3ab2dfb47f61.png">

**Comment by joshuasheppard** [comment]
Looking through this at 2PM instead of 2AM, I noticed that this appears to be a mismatch between the Chroma background-color, the border of the &lt;td&gt;, and the background of the page. 

Is this something wrong with what I did (I haven't edited the CSS directly), with the Beautiful Hugo theme interaction with Chroma, with the Hugo core interaction with Chroma, or with Chroma itself? Perhaps Chroma doesn't generate a "full width" &lt;tbody&gt; and it is only noticeable when the color of the borders don't match the background of both the Chroma div and the page.

If this is the wrong place to ask for this help, please let me know. I'm still quite new to Hugo.

**Comment by nancym** [comment]
I also have this problem. My guess is that it's a Chroma problem rather than a beautifulhugo problem, but I don't have time to try to figure this out right now. If anyone figures it out, please post!

**Comment by joshuasheppard** [comment]
Is the intent that code blocks extend the full width of the post? Or is it just expected to be wide enough for the code inside?

If the expectation is that it runs the full width, then the `<tbody>`, `<tr>`, and second `<td>` should extend the full width and currently the only do so if the code lines are long enough.

If the expectation is that the block is only as wide as necessary to contain the code, then the issue seems to be that in the following structure, the `<div class="chroma">` has a background-color but probably shouldn't. Because it does, the dark box on the far right of the image extends the entire width of the column rather than just the width of the code.
```
<div class="highlight">
  <div class="chroma">
    <table class="lntable">
      <tbody>
        <tr>
          <td class="lntd">
            <pre class="chroma">
              <code ...>
                <span class="lnt">
...
```

**Comment by joshuasheppard** [comment]
Posted question on [Hugo discussion forum](https://discourse.gohugo.io/t/chroma-highlighting-using-pygmentoptions-linenos-table-bug/9694).
